"""Add composite unique constraints

Revision ID: 8b35b3b39ce3
Revises: 76597a54f9fa
Create Date: 2026-07-22 00:30:07.691414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b35b3b39ce3'
down_revision: Union[str, Sequence[str], None] = '76597a54f9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_agency_member', 'ad_agency_memberships', ['user_id', 'agency_id'])
    op.create_unique_constraint('uq_client_member', 'ad_client_memberships', ['user_id', 'client_id'])
    op.create_unique_constraint('uq_project_member', 'ad_project_members', ['project_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_member', 'ad_project_members', type_='unique')
    op.drop_constraint('uq_client_member', 'ad_client_memberships', type_='unique')
    op.drop_constraint('uq_agency_member', 'ad_agency_memberships', type_='unique')
    # ### end Alembic commands ###
